# Stat the ssh-agent for handling ssh-key based auth
eval `ssh-agent`
ssh-add ~/.ssh/*.id_rsa

# Shortcuts to change latop display brightness
alias laptopDisplaySet='xrandr --output LVDS-1 --brightness 0.25'

# Shortcuts to turn on/off laptop display
alias laptopOff='xrandr --output LVDS-1 --off'
alias laptopOn='xrandr --output LVDS-1 --auto'

# Add GPG Keys to session
export GPG_TTY=$(tty)
